version: '3.8'

services:
  db:
    image: postgres:17
    container_name: mediquant-db
    environment:
      POSTGRES_DB: mediquant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-pgvector.sh:/docker-entrypoint-initdb.d/init-pgvector.sh
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: .
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mediquant_db
      - OLLAMA_BASE_URL=http://ollama:11434
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/test_detakmedis
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    env_file:
      - .env.example

volumes:
  pgdata:
  ollama_data: